/**
 * Коды бизнес-ошибок, используемые на backend и frontend
 */
export const ERROR_CODES = {
  // Общие ошибки
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  INVALID_OPERATION: 'INVALID_OPERATION',
  LIMIT_EXCEEDED: 'LIMIT_EXCEEDED',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',

  // Ошибки пользователя
  EMAIL_EXISTS: 'EMAIL_EXISTS',

  // OAuth ошибки
  OAUTH_PROVIDER_NOT_SUPPORTED: 'OAUTH_PROVIDER_NOT_SUPPORTED',
  OAUTH_ALREADY_LINKED: 'OAUTH_ALREADY_LINKED',
  OAUTH_NOT_FOUND: 'OAUTH_NOT_FOUND',
  CANNOT_UNLINK_LAST_AUTH: 'CANNOT_UNLINK_LAST_AUTH',
  OAUTH_STATE_INVALID: 'OAUTH_STATE_INVALID',
  OAUTH_CALLBACK_ERROR: 'OAUTH_CALLBACK_ERROR',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
