/**
 * Коды бизнес-ошибок, используемые на backend и frontend
 */
export const ERROR_CODES = {
  // Общие ошибки
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  INVALID_OPERATION: 'INVALID_OPERATION',
  LIMIT_EXCEEDED: 'LIMIT_EXCEEDED',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',

  // Ошибки пользователя
  EMAIL_EXISTS: 'EMAIL_EXISTS',

  // OAuth ошибки
  OAUTH_PROVIDER_NOT_SUPPORTED: 'OAUTH_PROVIDER_NOT_SUPPORTED',
  OAUTH_ALREADY_LINKED: 'OAUTH_ALREADY_LINKED',
  OAUTH_NOT_FOUND: 'OAUTH_NOT_FOUND',
  CANNOT_UNLINK_LAST_AUTH: 'CANNOT_UNLINK_LAST_AUTH',
  OAUTH_STATE_INVALID: 'OAUTH_STATE_INVALID',
  OAUTH_CALLBACK_ERROR: 'OAUTH_CALLBACK_ERROR',

  // Ошибки сайта
  SITE_NOT_FOUND: 'SITE_NOT_FOUND',
  SITE_NOT_OWNED: 'SITE_NOT_OWNED',

  // Ошибки краулинга
  CRAWL_INVALID_URL: 'CRAWL_INVALID_URL',
  CRAWL_BOT_DETECTED: 'CRAWL_BOT_DETECTED',
  CRAWL_NO_CONTENT: 'CRAWL_NO_CONTENT',
  CRAWL_INSUFFICIENT_PAGES: 'CRAWL_INSUFFICIENT_PAGES',
  CRAWL_ALREADY_IN_PROGRESS: 'CRAWL_ALREADY_IN_PROGRESS',
  CRAWL_RATE_LIMITED: 'CRAWL_RATE_LIMITED',

  // Ошибки виджета чата
  WIDGET_API_KEY_INVALID: 'WIDGET_API_KEY_INVALID',
  WIDGET_API_KEY_INACTIVE: 'WIDGET_API_KEY_INACTIVE',
  WIDGET_DOMAIN_MISMATCH: 'WIDGET_DOMAIN_MISMATCH',
  WIDGET_SESSION_LIMIT: 'WIDGET_SESSION_LIMIT',
  WIDGET_IP_LIMIT: 'WIDGET_IP_LIMIT',
  WIDGET_MESSAGE_NOT_FOUND: 'WIDGET_MESSAGE_NOT_FOUND',
  WIDGET_QUESTION_NOT_FOUND: 'WIDGET_QUESTION_NOT_FOUND',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
